USE [master]
GO

/****** Object:  Database [PS_GameLog]    Script Date: 10/02/2023 14:32:45 ******/
CREATE DATABASE [PS_GameLog]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PS_GameLog_Data', FILENAME = N'C:\ShaiyaServer\DB\PS_GameLog.mdf' , SIZE = 43456KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'PS_GameLog_Log', FILENAME = N'C:\ShaiyaServer\DB\PS_GameLog.ldf' , SIZE = 199296KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PS_GameLog].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [PS_GameLog] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PS_GameLog] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PS_GameLog] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PS_GameLog] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PS_GameLog] SET ARITHABORT OFF 
GO

ALTER DATABASE [PS_GameLog] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [PS_GameLog] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PS_GameLog] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PS_GameLog] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PS_GameLog] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PS_GameLog] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PS_GameLog] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PS_GameLog] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PS_GameLog] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PS_GameLog] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PS_GameLog] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PS_GameLog] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PS_GameLog] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PS_GameLog] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PS_GameLog] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PS_GameLog] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PS_GameLog] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PS_GameLog] SET RECOVERY FULL 
GO

ALTER DATABASE [PS_GameLog] SET  MULTI_USER 
GO

ALTER DATABASE [PS_GameLog] SET PAGE_VERIFY NONE  
GO

ALTER DATABASE [PS_GameLog] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PS_GameLog] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PS_GameLog] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [PS_GameLog] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PS_GameLog] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PS_GameLog] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PS_GameLog] SET  READ_WRITE 
GO

