SELECT 
	[RowID]
	,[ItemID]
	,[ItemName]
	,[Type]
	,[TypeID]
	,[Range]
	,[AttackTime]
	,[Attrib]
	,[Special]
	,[Slot]
	,[Quality]
	,[Effect1]
	,[Effect2]
	,[Effect3]
	,[Effect4]
	,[ConstHP]
	,[ConstSP]
	,[ConstMP]
	,[ConstStr]
	,[ConstDex]
	,[ConstRec]
	,[ConstInt]
	,[ConstWis]
	,[ConstLuc]
	,[Speed]
FROM [PS_GameDefs].[dbo].[Items]
where [Type] = 30 and TypeID >= 233 and TypeID <= 250 and TypeID not in (240,241,242,243)
order by Slot

