/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tool;

import SQL.Conexao;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorgi Luiz Bolonhezi Dias
 */
 
public class Account extends javax.swing.JFrame {

    /**
     * Creates new form Account
     */
    public Account() {
        initComponents();
        setSize(750, 309);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jUserUID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jCombo = new javax.swing.JComboBox();
        jOK = new javax.swing.JButton();
        jMenu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jResponsavel = new javax.swing.JTextField();
        jFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Account Status");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User UID:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(360, 70, 70, 30);
        getContentPane().add(jUserUID);
        jUserUID.setBounds(430, 70, 90, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Status:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(450, 100, 50, 30);

        jCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Active", "Banned 3 Days", "Banned 7 Days", "Banned 30 Days", "Banned 1 Year", "Permanent Ban" }));
        jCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboActionPerformed(evt);
            }
        });
        getContentPane().add(jCombo);
        jCombo.setBounds(360, 130, 200, 30);

        jOK.setBackground(new java.awt.Color(0, 51, 102));
        jOK.setForeground(new java.awt.Color(255, 255, 255));
        jOK.setText("OK");
        jOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOKActionPerformed(evt);
            }
        });
        getContentPane().add(jOK);
        jOK.setBounds(470, 10, 73, 23);

        jMenu.setBackground(new java.awt.Color(0, 51, 102));
        jMenu.setForeground(new java.awt.Color(255, 255, 255));
        jMenu.setText("Menu");
        jMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jMenu);
        jMenu.setBounds(550, 10, 80, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Responsible:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(430, 170, 90, 17);
        getContentPane().add(jResponsavel);
        jResponsavel.setBounds(410, 190, 140, 30);

        jFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LionNews.jpg"))); // NOI18N
        jFundo.setToolTipText("");
        getContentPane().add(jFundo);
        jFundo.setBounds(0, 0, 744, 282);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuActionPerformed
        new JBLogin().setVisible(true);
        this.dispose();
        this.setResizable(false);
    }//GEN-LAST:event_jMenuActionPerformed

    private void jOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOKActionPerformed
        try {
            if (jResponsavel.getText() != null) {
                if (jUserUID.getText() != null) {
                    if (jCombo.getSelectedIndex() == 0) {
                        Conexao con = new Conexao();
                        String SQL = "Update PS_UserData.dbo.Users_Master set Status=0 where UserUID=?";
                        PreparedStatement ps = con.getConexao().prepareStatement(SQL);
                        ps.setString(1, jUserUID.getText());
                        int registros = ps.executeUpdate();
                        if (registros > 0) {
                            JOptionPane.showMessageDialog(null, "Updated");
                            String data = "dd/MM/yyyy";
                            String hora = "h:mm - a";
                            String data1, hora1;
                            java.util.Date agora = new java.util.Date();;
                            SimpleDateFormat formata = new SimpleDateFormat(data);
                            data1 = formata.format(agora);
                            formata = new SimpleDateFormat(hora);
                            hora1 = formata.format(agora);
                            Conexao con1 = new Conexao();
                            String SQL1 = "INSERT INTO PS_ActionPerformed.dbo.Action values(?,'Account',?,?,?)";
                            PreparedStatement ps1 = con1.getConexao().prepareStatement(SQL1);
                            ps1.setString(1, jResponsavel.getText());
                            ps1.setString(2, data1);
                            ps1.setString(3, hora1);
                            ps1.setString(4, jResponsavel.getText());
                            int registros1 = ps1.executeUpdate();
                            jUserUID.setText("");
                            jResponsavel.setText("");
                        } else {
                            JOptionPane.showMessageDialog(null, "Invalid Time.");;
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Please Insert UserUID");
                    }
                    if (jCombo.getSelectedIndex() == 1) {
                        Conexao con = new Conexao();
                        String SQL = "Update PS_UserData.dbo.Users_Master set Status=-5 where UserUID=?";
                        PreparedStatement ps = con.getConexao().prepareStatement(SQL);
                        ps.setString(1, jUserUID.getText());
                        int registros = ps.executeUpdate();
                        if (registros > 0) {
                            JOptionPane.showMessageDialog(null, "Updated");
                            String data = "dd/MM/yyyy";
                            String hora = "h:mm - a";
                            String data1, hora1;
                            java.util.Date agora = new java.util.Date();;
                            SimpleDateFormat formata = new SimpleDateFormat(data);
                            data1 = formata.format(agora);
                            formata = new SimpleDateFormat(hora);
                            hora1 = formata.format(agora);
                            Conexao con1 = new Conexao();
                            String SQL1 = "INSERT INTO PS_ActionPerformed.dbo.Action values(?,'Account',?,?,?)";
                            PreparedStatement ps1 = con1.getConexao().prepareStatement(SQL1);
                            ps1.setString(1, jResponsavel.getText());
                            ps1.setString(2, data1);
                            ps1.setString(3, hora1);
                            ps1.setString(4, jResponsavel.getText());
                            int registros1 = ps1.executeUpdate();
                            jUserUID.setText("");
                            jResponsavel.setText("");
                        } else {
                            JOptionPane.showMessageDialog(null, "Invalid Time.");;
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Please Insert UserUID");
                    }
                    if (jCombo.getSelectedIndex() == 2) {
                        Conexao con = new Conexao();
                        String SQL = "Update PS_UserData.dbo.Users_Master set Status=-5 where UserUID=?";
                        PreparedStatement ps = con.getConexao().prepareStatement(SQL);
                        ps.setString(1, jUserUID.getText());
                        int registros = ps.executeUpdate();
                        if (registros > 0) {
                            JOptionPane.showMessageDialog(null, "Updated");
                            String data = "dd/MM/yyyy";
                            String hora = "h:mm - a";
                            String data1, hora1;
                            java.util.Date agora = new java.util.Date();;
                            SimpleDateFormat formata = new SimpleDateFormat(data);
                            data1 = formata.format(agora);
                            formata = new SimpleDateFormat(hora);
                            hora1 = formata.format(agora);
                            Conexao con1 = new Conexao();
                            String SQL1 = "INSERT INTO PS_ActionPerformed.dbo.Action values(?,'Account',?,?,?)";
                            PreparedStatement ps1 = con1.getConexao().prepareStatement(SQL1);
                            ps1.setString(1, jResponsavel.getText());
                            ps1.setString(2, data1);
                            ps1.setString(3, hora1);
                            ps1.setString(4, jResponsavel.getText());
                            int registros1 = ps1.executeUpdate();
                            jUserUID.setText("");
                            jResponsavel.setText("");
                        } else {
                            JOptionPane.showMessageDialog(null, "Invalid Time.");;
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Please Insert UserUID");
                    }
                    if (jCombo.getSelectedIndex() == 3) {
                        Conexao con = new Conexao();
                        String SQL = "Update PS_UserData.dbo.Users_Master set Status=-5 where UserUID=?";
                        PreparedStatement ps = con.getConexao().prepareStatement(SQL);
                        ps.setString(1, jUserUID.getText());
                        int registros = ps.executeUpdate();
                        if (registros > 0) {
                            JOptionPane.showMessageDialog(null, "Updated");
                            String data = "dd/MM/yyyy";
                            String hora = "h:mm - a";
                            String data1, hora1;
                            java.util.Date agora = new java.util.Date();;
                            SimpleDateFormat formata = new SimpleDateFormat(data);
                            data1 = formata.format(agora);
                            formata = new SimpleDateFormat(hora);
                            hora1 = formata.format(agora);
                            Conexao con1 = new Conexao();
                            String SQL1 = "INSERT INTO PS_ActionPerformed.dbo.Action values(?,'Account',?,?,?)";
                            PreparedStatement ps1 = con1.getConexao().prepareStatement(SQL1);
                            ps1.setString(1, jResponsavel.getText());
                            ps1.setString(2, data1);
                            ps1.setString(3, hora1);
                            ps1.setString(4, jResponsavel.getText());
                            int registros1 = ps1.executeUpdate();
                            jUserUID.setText("");
                            jResponsavel.setText("");
                        } else {
                            JOptionPane.showMessageDialog(null, "Invalid Time.");;
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Please Insert UserUID");
                    }
                    if (jCombo.getSelectedIndex() == 4) {
                        Conexao con = new Conexao();
                        String SQL = "Update PS_UserData.dbo.Users_Master set Status=-5 where UserUID=?";
                        PreparedStatement ps = con.getConexao().prepareStatement(SQL);
                        ps.setString(1, jUserUID.getText());
                        int registros = ps.executeUpdate();
                        if (registros > 0) {
                            JOptionPane.showMessageDialog(null, "Updated");
                            String data = "dd/MM/yyyy";
                            String hora = "h:mm - a";
                            String data1, hora1;
                            java.util.Date agora = new java.util.Date();;
                            SimpleDateFormat formata = new SimpleDateFormat(data);
                            data1 = formata.format(agora);
                            formata = new SimpleDateFormat(hora);
                            hora1 = formata.format(agora);
                            Conexao con1 = new Conexao();
                            String SQL1 = "INSERT INTO PS_ActionPerformed.dbo.Action values(?,'Account',?,?,?)";
                            PreparedStatement ps1 = con1.getConexao().prepareStatement(SQL1);
                            ps1.setString(1, jResponsavel.getText());
                            ps1.setString(2, data1);
                            ps1.setString(3, hora1);
                            ps1.setString(4, jResponsavel.getText());
                            int registros1 = ps1.executeUpdate();
                            jUserUID.setText("");
                            jResponsavel.setText("");
                        } else {
                            JOptionPane.showMessageDialog(null, "Invalid Time.");;
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Please Insert UserUID");
                    }
                    if (jCombo.getSelectedIndex() == 5) {
                        Conexao con = new Conexao();
                        String SQL = "Update PS_UserData.dbo.Users_Master set Status=-5 where UserUID=?";
                        PreparedStatement ps = con.getConexao().prepareStatement(SQL);
                        ps.setString(1, jUserUID.getText());
                        int registros = ps.executeUpdate();
                        if (registros > 0) {
                            JOptionPane.showMessageDialog(null, "Updated");
                            String data = "dd/MM/yyyy";
                            String hora = "h:mm - a";
                            String data1, hora1;
                            java.util.Date agora = new java.util.Date();;
                            SimpleDateFormat formata = new SimpleDateFormat(data);
                            data1 = formata.format(agora);
                            formata = new SimpleDateFormat(hora);
                            hora1 = formata.format(agora);
                            Conexao con1 = new Conexao();
                            String SQL1 = "INSERT INTO PS_ActionPerformed.dbo.Action values(?,'Account',?,?,?)";
                            PreparedStatement ps1 = con1.getConexao().prepareStatement(SQL1);
                            ps1.setString(1, jResponsavel.getText());
                            ps1.setString(2, data1);
                            ps1.setString(3, hora1);
                            ps1.setString(4, jResponsavel.getText());
                            int registros1 = ps1.executeUpdate();
                            jUserUID.setText("");
                            jResponsavel.setText("");
                        } else {
                            JOptionPane.showMessageDialog(null, "Invalid Time.");;
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Please Insert UserUID");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please Insert Responsible");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Connection Error");
        }
    }//GEN-LAST:event_jOKActionPerformed

    private void jComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jCombo;
    private javax.swing.JLabel jFundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jMenu;
    private javax.swing.JButton jOK;
    private javax.swing.JTextField jResponsavel;
    private javax.swing.JTextField jUserUID;
    // End of variables declaration//GEN-END:variables
}
