/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tool;

import SQL.Conexao;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorgi Luiz Bolonhezi Dias
 */
 
public class Actions extends javax.swing.JFrame {

    /**
     * Creates new form Actions
     */
    public Actions() {
        initComponents();
        setSize(750, 309);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Report = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jNext = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Number = new javax.swing.JTextField();
        jFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Actions - Panel");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Action:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(430, 0, 70, 40);

        Report.setColumns(20);
        Report.setRows(5);
        jScrollPane1.setViewportView(Report);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(490, 10, 240, 140);

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(450, 230, 100, 23);

        jNext.setBackground(new java.awt.Color(0, 51, 102));
        jNext.setForeground(new java.awt.Color(255, 255, 255));
        jNext.setText("GO");
        jNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNextActionPerformed(evt);
            }
        });
        getContentPane().add(jNext);
        jNext.setBounds(490, 160, 60, 30);

        jButton3.setBackground(new java.awt.Color(0, 0, 102));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(560, 230, 80, 23);
        getContentPane().add(Number);
        Number.setBounds(420, 160, 59, 30);

        jFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LionNews.jpg"))); // NOI18N
        getContentPane().add(jFundo);
        jFundo.setBounds(0, 0, 744, 282);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Conexao con = new Conexao();
            String SQL = "SELECT top 100 UserUID, Action, Date, Time, Responsible from PS_ActionPerformed.dbo.Action";
            PreparedStatement ps = con.getConexao().prepareStatement(SQL);
            ResultSet registros = ps.executeQuery();
            registros.next();
            String Am = registros.getString("UserUID");
            String Am1 = registros.getString("Action");
            String Am2 = registros.getString("Date");
            String Am3 = registros.getString("Time");
            String Am4 = registros.getString("Responsible");
            if (Am != null) {
                Report.setText("UserUID:" + Am + " "
                        + "\nAction:" + Am1 + ""
                        + "\nDate:" + Am2 + " "
                        + "\nTime:" + Am3 + " "
                        + "\nResponsible: " + Am4);
            } else {
                JOptionPane.showMessageDialog(null, "Not Found");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: Not Found");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNextActionPerformed

        try {
            Conexao con = new Conexao();
            String SQL = "SELECT top 100 UserUID, Action, Date, Time, Responsible from PS_ActionPerformed.dbo.Action";
            PreparedStatement ps = con.getConexao().prepareStatement(SQL);
            ResultSet registros = ps.executeQuery();
            int h = Integer.parseInt(Number.getText());
            for (int i = 0; i < h; i++) {
                registros.next();
            }
            String Am = registros.getString("UserUID");
            String Am1 = registros.getString("Action");
            String Am2 = registros.getString("Date");
            String Am3 = registros.getString("Time");
            String Am4 = registros.getString("Responsible");
            if (Am != null) {
                Report.setText("UserUID:" + Am + " "
                        + "\nAction:" + Am1 + ""
                        + "\nDate:" + Am2 + " "
                        + "\nTime:" + Am3 + " "
                        + "\nResponsible: " + Am4);
            } else {
                JOptionPane.showMessageDialog(null, "Error: This Registry Doesnt Exist");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: This Registry Doesnt Exist");
        }
    }//GEN-LAST:event_jNextActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                new JBLogin().setVisible(true);
                this.dispose();
                this.setResizable(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Number;
    private javax.swing.JTextArea Report;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jFundo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jNext;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
