/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tool;

import SQL.Conexao;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorgi Luiz Bolonhezi Dias
 */
 
public class Buyers extends javax.swing.JFrame {

    /**
     * Creates new form Buyers
     */
    public Buyers() {
        initComponents();
        setSize(750, 310);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSearch = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jMost = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jWeak = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jBest = new javax.swing.JTextField();
        jMenu = new javax.swing.JButton();
        jFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buyer - Panel");
        setResizable(false);
        getContentPane().setLayout(null);

        jSearch.setBackground(new java.awt.Color(0, 51, 102));
        jSearch.setForeground(new java.awt.Color(255, 255, 255));
        jSearch.setText("Search");
        jSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchActionPerformed(evt);
            }
        });
        getContentPane().add(jSearch);
        jSearch.setBounds(560, 20, 80, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Most Sold:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(380, 20, 73, 30);
        getContentPane().add(jMost);
        jMost.setBounds(470, 20, 70, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Weak Sold:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(380, 60, 80, 30);
        getContentPane().add(jWeak);
        jWeak.setBounds(470, 60, 70, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Best Buyer:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(380, 100, 90, 30);
        getContentPane().add(jBest);
        jBest.setBounds(470, 100, 70, 30);

        jMenu.setBackground(new java.awt.Color(0, 51, 102));
        jMenu.setForeground(new java.awt.Color(255, 255, 255));
        jMenu.setText("Menu");
        jMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jMenu);
        jMenu.setBounds(650, 20, 80, 23);

        jFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LionNews.jpg"))); // NOI18N
        getContentPane().add(jFundo);
        jFundo.setBounds(0, 0, 744, 282);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchActionPerformed
         try {
                Conexao con = new Conexao();
                String SQL = "SELECT TOP 1 UserUID from PS_GameData.dbo.PointLog where UsePoint<>0";
                PreparedStatement ps = con.getConexao().prepareStatement(SQL);
                ResultSet registros = ps.executeQuery();
                registros.next();
                String Am = registros.getString("UserUID");
                if(Am!=null){
                    jBest.setText(Am);
                }else{
                    JOptionPane.showMessageDialog(null, "Not Found");
                }
                SQL = "SELECT TOP 100 ProductCode from PS_GameData.dbo.PointLog where UsePoint<>0";
                ps = con.getConexao().prepareStatement(SQL);
                registros = ps.executeQuery();
                for(int i = 0; i<100; i++){
                registros.next();
                }
                Am = registros.getString("ProductCode");
                if(Am!=null){
                    jWeak.setText(Am);
                }else{
                    JOptionPane.showMessageDialog(null, "Not Found");
                }
                SQL = "SELECT TOP 1 ProductCode from PS_GameData.dbo.PointLog where UsePoint<>0";
                ps = con.getConexao().prepareStatement(SQL);
                registros = ps.executeQuery();
                registros.next();
                Am = registros.getString("ProductCode");
                if(Am!=null){
                    jMost.setText(Am);
                }else{
                    JOptionPane.showMessageDialog(null, "Not Found");
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: Not Found");
        }

    }//GEN-LAST:event_jSearchActionPerformed

    private void jMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuActionPerformed
                new JBLogin().setVisible(true);
                this.dispose();
                this.setResizable(false);
    }//GEN-LAST:event_jMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buyers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buyers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buyers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buyers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buyers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jBest;
    private javax.swing.JLabel jFundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jMenu;
    private javax.swing.JTextField jMost;
    private javax.swing.JToggleButton jSearch;
    private javax.swing.JTextField jWeak;
    // End of variables declaration//GEN-END:variables
}
