/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tool;

import SQL.Conexao;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorgi Luiz Bolonhezi Dias
 */
 
public class Character extends javax.swing.JFrame {

    /**
     * Creates new form Character
     */
    public Character() {
        initComponents();
        setSize(750, 310);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jName = new javax.swing.JTextField();
        jNewName = new javax.swing.JTextField();
        REC = new javax.swing.JTextField();
        STR = new javax.swing.JTextField();
        INT = new javax.swing.JTextField();
        WIS = new javax.swing.JTextField();
        LUC = new javax.swing.JTextField();
        jLevel = new javax.swing.JTextField();
        jMap = new javax.swing.JTextField();
        DEX = new javax.swing.JTextField();
        KILLS = new javax.swing.JTextField();
        DEATHS = new javax.swing.JTextField();
        VICTORY = new javax.swing.JTextField();
        LOSERS = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jResponsavel = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Menu = new javax.swing.JButton();
        jFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Character");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name:");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 50, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("New Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 50, 90, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Map:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 90, 40, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Level:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 130, 50, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("STR:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 170, 33, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DEX:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 210, 34, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("LUC:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(340, 90, 34, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("REC:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(200, 90, 34, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("INT:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(200, 210, 34, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("WIS:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(340, 40, 40, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Kills:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(470, 40, 40, 30);
        getContentPane().add(jName);
        jName.setBounds(70, 10, 130, 30);

        jNewName.setEnabled(false);
        jNewName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNewNameActionPerformed(evt);
            }
        });
        getContentPane().add(jNewName);
        jNewName.setBounds(100, 50, 130, 30);

        REC.setEnabled(false);
        getContentPane().add(REC);
        REC.setBounds(240, 90, 60, 30);

        STR.setEnabled(false);
        getContentPane().add(STR);
        STR.setBounds(100, 170, 60, 30);

        INT.setEnabled(false);
        INT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INTActionPerformed(evt);
            }
        });
        getContentPane().add(INT);
        INT.setBounds(240, 210, 60, 30);

        WIS.setEnabled(false);
        getContentPane().add(WIS);
        WIS.setBounds(380, 40, 60, 30);

        LUC.setEnabled(false);
        getContentPane().add(LUC);
        LUC.setBounds(380, 90, 60, 30);

        jLevel.setEnabled(false);
        getContentPane().add(jLevel);
        jLevel.setBounds(100, 130, 60, 30);

        jMap.setEnabled(false);
        getContentPane().add(jMap);
        jMap.setBounds(100, 90, 60, 30);

        DEX.setEnabled(false);
        getContentPane().add(DEX);
        DEX.setBounds(100, 210, 60, 30);

        KILLS.setEnabled(false);
        getContentPane().add(KILLS);
        KILLS.setBounds(530, 40, 60, 30);

        DEATHS.setEnabled(false);
        getContentPane().add(DEATHS);
        DEATHS.setBounds(530, 90, 60, 30);

        VICTORY.setEnabled(false);
        VICTORY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VICTORYActionPerformed(evt);
            }
        });
        getContentPane().add(VICTORY);
        VICTORY.setBounds(530, 130, 60, 30);

        LOSERS.setEnabled(false);
        getContentPane().add(LOSERS);
        LOSERS.setBounds(530, 170, 60, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Deaths:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(460, 90, 60, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Victory:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(460, 130, 54, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Losers:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(460, 170, 50, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Responsible:");
        jLabel15.setToolTipText("");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(430, 210, 87, 30);

        jResponsavel.setEnabled(false);
        getContentPane().add(jResponsavel);
        jResponsavel.setBounds(530, 210, 150, 30);

        Search.setBackground(new java.awt.Color(0, 51, 153));
        Search.setForeground(new java.awt.Color(255, 255, 255));
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search);
        Search.setBounds(630, 10, 90, 23);

        Update.setBackground(new java.awt.Color(0, 51, 153));
        Update.setForeground(new java.awt.Color(255, 255, 255));
        Update.setText("Update");
        Update.setEnabled(false);
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update);
        Update.setBounds(630, 50, 90, 23);

        Menu.setBackground(new java.awt.Color(0, 51, 153));
        Menu.setForeground(new java.awt.Color(255, 255, 255));
        Menu.setText("Menu");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });
        getContentPane().add(Menu);
        Menu.setBounds(630, 90, 90, 23);

        jFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LionNews.jpg"))); // NOI18N
        getContentPane().add(jFundo);
        jFundo.setBounds(0, 0, 744, 282);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNewNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNewNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNewNameActionPerformed

    private void INTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_INTActionPerformed

    private void VICTORYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VICTORYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VICTORYActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        try{        
                Conexao con = new Conexao();
                String SQL = "SELECT * from PS_GameData.dbo.Chars WHERE CharName=?";
                PreparedStatement ps = con.getConexao().prepareStatement(SQL);
                ps.setString(1, jName.getText());
                ResultSet registros = ps.executeQuery();
                registros.next();
                String Char = registros.getString("CharName");
                int Level = registros.getInt("Level");
                int Kills2 = registros.getInt("K1");
                int Mortes2 = registros.getInt("K2");
                int Map2 = registros.getInt("Map");
                int str2 = registros.getInt("Str");
                int dex2 = registros.getInt("Dex");
                int luc2 = registros.getInt("Luc");
                int rec2 = registros.getInt("Rec");
                int int2 = registros.getInt("Int");
                int wis2 = registros.getInt("Wis");
                int Vic2 = registros.getInt("K3");
                int Lo2 = registros.getInt("K4");
                if(Char!=null){
                    String Vic = Integer.toString(Vic2);
                    VICTORY.setText(Vic);
                    VICTORY.setEnabled(true);
                    String Lo = Integer.toString(Lo2);
                    LOSERS.setText(Lo);
                    LOSERS.setEnabled(true);
                    jName.setText(Char);
                    jNewName.setEnabled(true);
                    jNewName.setText(Char);
                    String Kills = Integer.toString(Kills2);
                    KILLS.setText(Kills);
                    KILLS.setEnabled(true);
                    String Mortes1 = Integer.toString(Mortes2);
                    DEATHS.setText(Mortes1);
                    DEATHS.setEnabled(true);
                    String Map1 = Integer.toString(Map2);
                    jMap.setText(Map1);
                    jMap.setEnabled(true);
                    String str1 = Integer.toString(str2);
                    STR.setText(str1);
                    STR.setEnabled(true);
                    String dex1 = Integer.toString(dex2);
                    DEX.setText(dex1);
                    DEX.setEnabled(true);
                    String luc1 = Integer.toString(luc2);
                    LUC.setText(luc1);
                    LUC.setEnabled(true);
                    String rec1 = Integer.toString(rec2);
                    REC.setText(rec1);
                    REC.setEnabled(true);
                    String int1 = Integer.toString(int2);
                    INT.setText(int1);
                    INT.setEnabled(true);
                    String wis1 = Integer.toString(wis2);
                    WIS.setText(wis1);
                    WIS.setEnabled(true);
                    String Level1 = Integer.toString(Level);
                    jLevel.setText(Level1);
                    jLevel.setEnabled(true);
                    jResponsavel.setEnabled(true);
                    Update.setEnabled(true);
                    jName.setEnabled(false);
                    Search.setEnabled(false);
                }else{
                    JOptionPane.showMessageDialog(null, "Mob Not Found");
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: Not Found");
        }

    }//GEN-LAST:event_SearchActionPerformed

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
            new JBLogin().setVisible(true);
            this.dispose();
            this.setResizable(false);
    }//GEN-LAST:event_MenuActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
                  try {
            if (jName.getText() != null) {
                if (jNewName.getText() != null) {
                    Conexao con = new Conexao();
                    String SQL = "UPDATE PS_GameData.dbo.Chars SET CharName=?, K1=?, K2=?, K3=?, K4=?, Map=?, Str=?, Dex=?, Luc=?, Rec=?, Int=?, Wis=?, Level=? WHERE CharName=?";
                    PreparedStatement ps = con.getConexao().prepareStatement(SQL);
                    ps.setString(1, jNewName.getText());
                    ps.setString(2, KILLS.getText());
                    ps.setString(3, DEATHS.getText());
                    ps.setString(4, VICTORY.getText());
                    ps.setString(5, LOSERS.getText());
                    ps.setString(6, jMap.getText());
                    ps.setString(7, STR.getText());
                    ps.setString(8, DEX.getText());
                    ps.setString(9, LUC.getText());
                    ps.setString(10, REC.getText());
                    ps.setString(11, INT.getText());
                    ps.setString(12, WIS.getText());
                    ps.setString(13, jLevel.getText());
                    ps.setString(14, jName.getText());
                    int registros = ps.executeUpdate();
                    if (registros > 0) {
                        JOptionPane.showMessageDialog(null, "Changed Sucessfully.");
                        String data = "dd/MM/yyyy";
                        String hora = "h:mm - a";
                        String data1, hora1;
                        java.util.Date agora = new java.util.Date();
                        SimpleDateFormat formata = new SimpleDateFormat(data);
                        data1 = formata.format(agora);
                        formata = new SimpleDateFormat(hora);
                        hora1 = formata.format(agora);
                        Conexao con1 = new Conexao();
                        String SQL1 = "INSERT INTO PS_ActionPerformed.dbo.Action values(?,'Edit Toon',?,?,?)";
                        PreparedStatement ps1 = con1.getConexao().prepareStatement(SQL1);
                        ps1.setString(1, jResponsavel.getText());
                        ps1.setString(2, data1);
                        ps1.setString(3, hora1);
                        ps1.setString(4, jResponsavel.getText());
                        ps1.executeUpdate();
                        jName.setText("");
                        jNewName.setText("");
                        jNewName.setEnabled(false);
                        jResponsavel.setText("");
                        jResponsavel.setEnabled(false);
                        jNewName.setText("");
                        jNewName.setEnabled(false);
                        KILLS.setText("");
                        KILLS.setEnabled(false);
                        DEATHS.setText("");
                        DEATHS.setEnabled(false);
                        jMap.setText("");
                        jMap.setEnabled(false);
                        STR.setText("");
                        STR.setEnabled(false);
                        DEX.setText("");
                        DEX.setEnabled(false);
                        LUC.setText("");
                        LUC.setEnabled(false);
                        REC.setText("");
                        REC.setEnabled(false);
                        INT.setText("");
                        INT.setEnabled(false);
                        WIS.setText("");
                        WIS.setEnabled(false);
                        jLevel.setText("");
                        jLevel.setEnabled(false);
                        jName.setText("");
                        jResponsavel.setEnabled(false);
                        Search.setEnabled(false);
                        jName.setEnabled(true);
                        Search.setEnabled(true);
                        VICTORY.setText("");
                        VICTORY.setEnabled(false);
                        LOSERS.setText("");
                        LOSERS.setEnabled(false);
                    } else {
                        JOptionPane.showMessageDialog(null, "Invalid Name.");;
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Please Insert New Toon Name");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please Insert Toon Name");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please Insert Valid Numbers");
        }



    }//GEN-LAST:event_UpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Character.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Character.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Character.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Character.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Character().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DEATHS;
    private javax.swing.JTextField DEX;
    private javax.swing.JTextField INT;
    private javax.swing.JTextField KILLS;
    private javax.swing.JTextField LOSERS;
    private javax.swing.JTextField LUC;
    private javax.swing.JButton Menu;
    private javax.swing.JTextField REC;
    private javax.swing.JTextField STR;
    private javax.swing.JButton Search;
    private javax.swing.JButton Update;
    private javax.swing.JTextField VICTORY;
    private javax.swing.JTextField WIS;
    private javax.swing.JLabel jFundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLevel;
    private javax.swing.JTextField jMap;
    private javax.swing.JTextField jName;
    private javax.swing.JTextField jNewName;
    private javax.swing.JTextField jResponsavel;
    // End of variables declaration//GEN-END:variables
}
