/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tool;

import SQL.Conexao;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorgi Luiz Bolonhezi Dias
 */
 
public class Consult extends javax.swing.JFrame {

    /**
     * Creates new form Consult
     */
    public Consult() {
        initComponents();
        setSize(750, 310);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MobID = new javax.swing.JLabel();
        MobName = new javax.swing.JTextField();
        ItemName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ItemID = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consult - Panel");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mob Name:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 20, 90, 30);

        MobID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MobID.setForeground(new java.awt.Color(255, 255, 255));
        MobID.setText("Mob Id: Searching");
        getContentPane().add(MobID);
        MobID.setBounds(590, 20, 140, 30);
        getContentPane().add(MobName);
        MobName.setBounds(480, 20, 100, 30);
        getContentPane().add(ItemName);
        ItemName.setBounds(480, 60, 100, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Item Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(390, 60, 90, 30);

        ItemID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ItemID.setForeground(new java.awt.Color(255, 255, 255));
        ItemID.setText("Item Id: Searching");
        getContentPane().add(ItemID);
        ItemID.setBounds(590, 60, 140, 30);

        jButton1.setBackground(new java.awt.Color(0, 51, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 30, 100, 23);

        jButton2.setBackground(new java.awt.Color(0, 51, 102));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(250, 60, 100, 23);

        jButton3.setBackground(new java.awt.Color(0, 51, 102));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(250, 90, 100, 23);

        jFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LionNews.jpg"))); // NOI18N
        getContentPane().add(jFundo);
        jFundo.setBounds(0, 0, 744, 282);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            try{        
                Conexao con = new Conexao();
                String SQL = "select * from PS_GameDefs.dbo.Mobs where MobName=?";
                PreparedStatement ps = con.getConexao().prepareStatement(SQL);
                ps.setString(1, MobName.getText());
                ResultSet registros = ps.executeQuery();
                registros.next();
                int Am = registros.getInt("MobID");
                if(Am!=0){
                    String Am1 = Integer.toString(Am);
                    MobID.setText("Mob Id:"+Am1);
                    MobName.setText("");
                }else{
                    JOptionPane.showMessageDialog(null, "Mob Not Found");
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: Not Found");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            try{        
                Conexao con = new Conexao();
                String SQL = "select * from PS_GameDefs.dbo.Items where ItemName=?";
                PreparedStatement ps = con.getConexao().prepareStatement(SQL);
                ps.setString(1, ItemName.getText());
                ResultSet registros = ps.executeQuery();
                registros.next();
                int Am = registros.getInt("ItemID");
                if(Am!=0){
                    String Am1 = Integer.toString(Am);
                    ItemID.setText("Item Id:"+Am1);
                    ItemName.setText("");
                }else{
                    JOptionPane.showMessageDialog(null, "Item Not Found");
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: Not Found");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                new JBLogin().setVisible(true);
                this.dispose();
                this.setResizable(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ItemID;
    private javax.swing.JTextField ItemName;
    private javax.swing.JLabel MobID;
    private javax.swing.JTextField MobName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jFundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
