/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tool;

/**
 *
 * @author Jorgi Luiz Bolonhezi Dias
 */
 
public class DropList extends javax.swing.JFrame {

    /**
     * Creates new form DropList
     */
    public DropList() {
        initComponents();
        setSize(750, 309);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMake = new javax.swing.JButton();
        jMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jText = new javax.swing.JTextArea();
        jFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Drop List - Panel");
        setResizable(false);
        getContentPane().setLayout(null);

        jMake.setBackground(new java.awt.Color(0, 51, 102));
        jMake.setForeground(new java.awt.Color(255, 255, 255));
        jMake.setText("Search");
        jMake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMakeActionPerformed(evt);
            }
        });
        getContentPane().add(jMake);
        jMake.setBounds(430, 220, 110, 23);

        jMenu.setBackground(new java.awt.Color(0, 51, 102));
        jMenu.setForeground(new java.awt.Color(255, 255, 255));
        jMenu.setText("Menu");
        jMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jMenu);
        jMenu.setBounds(629, 220, 90, 23);

        jText.setColumns(20);
        jText.setRows(5);
        jScrollPane1.setViewportView(jText);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(430, 10, 310, 200);

        jFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LionNews.jpg"))); // NOI18N
        getContentPane().add(jFundo);
        jFundo.setBounds(0, 0, 744, 282);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuActionPerformed
                new JBLogin().setVisible(true);
                this.dispose();
                this.setResizable(false);
    }//GEN-LAST:event_jMenuActionPerformed

    private void jMakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMakeActionPerformed
                jText.setText("MONSTER	DROP	DROPRATE\n" +
"OI Mobs	1x Lapis Lv8, 20-50 DP Tickets, Lv2 Acessorie Lapis, Dual Lv5, Dual Lv6, Helmet Lapis Lv2, Fortune Coin Lv5, Paradise Hammer, Island Hammer	50%\n" +
"Map 2 and 3 Mobs	1x Piece of Gears or Weapon Lv70	10%\n" +
"Pantanasa Mobs	1x Lapis Lv8, Battleground Rune, Perfect Paradise Box, Fortune Coin Lv3, Paradise Attack Lapis, Paradise Cure Lapis	100%\n" +
"Theodores Mobs	1x Lapis Lv8, Battleground Rune, Perfect Paradise Box, Fortune Coin Lv3, Paradise Attack Lapis, Paradise Cure Lapis	100%\n" +
"DD1 Mobs	1x Elemental Lapis Lv2	20%\n" +
"Stable Erde Mobs	1x Elemental Lapis Lv2	20%\n" +
"All Mobs	1x Nostruns or Fortune Coin Lv4	15%\n" +
"KI Bosses	1x Piece of Gears Lv71-77; 1x Piece of Weapons Lv75-78; 1x Perfection Orange Stats or 100-1000 DP Ticket	100%\n" +
"KI Golems	1x Perfect Lapisia, Perfect Paradise Box	15%\n" +
"Opalus	1x Piece of Gears Lv71-77; 1x Piece of Weapons Lv75-78; 1x Perfection Orange Stats or 100-1000 DP Ticket	100%\n" +
"Light Goddess	1x Piece of Gears Lv71-77; 1x Piece of Weapons Lv75-78; 1x Perfection Orange Stats or 100-1000 DP Ticket	100%\n" +
"Fury Goddess	1x Piece of Gears Lv71-77; 1x Piece of Weapons Lv75-78; 1x Perfection Orange Stats or 100-1000 DP Ticket	100%\n" +
"CTI Bosses	2x Piece of Gears Lv80(1x Light and 1x Fury)	100%\n" +
"Dios Exiel	2x Piece of Gears Lv80(1x Light and 1x Fury)	100%\n" +
"Kimuraku	1x Piece of Gears or Weapon Lv64-69	100%\n" +
"Fantasma Dragon	1x Piece of Gears or Weapon Lv64-69	100%\n" +
"Cloron Dragon	1x Piece of Gears or Weapon Lv64-69	100%\n" +
"Fantasma Dragon	1x Piece of Gears or Weapon Lv64-69	100%\n" +
"Seraphim	1x Piece of Gears or Weapon Lv64-69	100%\n" +
"Freezing Miragem	1x Golden Accessorie	100%\n" +
"Haruhion	1x Golden Accessorie	100%\n" +
"Fabric	1x Piece of Gears Lv71-77; 1x Piece of Weapons Lv75-78; 1x Perfection Orange Stats or 100-1000 DP Ticket	100%\n" +
"OI Bosses	1x Special Acessorie Lapis	100%\n" +
"Rapioru Duplicate	1x Piece of Weapon or Gear Lv70 (Elemental Tops)	100%\n" +
"Corrupted Paros	1x Piece of Weapon or Gear Lv70 (Elemental Tops)	100%\n" +
"Mystra's Queen	1x Cape Lv70; Little Chance for Debuff Lapis	100%");
    }//GEN-LAST:event_jMakeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DropList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DropList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DropList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DropList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DropList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jFundo;
    private javax.swing.JButton jMake;
    private javax.swing.JButton jMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jText;
    // End of variables declaration//GEN-END:variables
}
