/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tool;

import SQL.Conexao;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorgi Luiz Bolonhezi Dias
 */
 
public class EditItem extends javax.swing.JFrame {

    /**
     * Creates new form EditItem
     */
    public EditItem() {
        initComponents();
        setSize(750, 310);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        UserUID = new javax.swing.JTextField();
        Lapis2 = new javax.swing.JTextField();
        ItemID = new javax.swing.JTextField();
        Lapis4 = new javax.swing.JTextField();
        Lapis3 = new javax.swing.JTextField();
        Type = new javax.swing.JTextField();
        TypeID = new javax.swing.JTextField();
        Lapis1 = new javax.swing.JTextField();
        strrr = new javax.swing.JTextField();
        Lapis5 = new javax.swing.JTextField();
        Lapis6 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        recrr = new javax.swing.JTextField();
        lucrr = new javax.swing.JTextField();
        intrr = new javax.swing.JTextField();
        wisrr = new javax.swing.JTextField();
        dexrr = new javax.swing.JTextField();
        EnchantType = new javax.swing.JComboBox();
        Search = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        hprr = new javax.swing.JTextField();
        sprr = new javax.swing.JTextField();
        mprr = new javax.swing.JTextField();
        Responsavel = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        JFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Item - Panel");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User UID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 60, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Item ID:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 50, 60, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Type:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(18, 90, 40, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lapis 3:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 10, 50, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TypeID:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(14, 130, 50, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("STR:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(210, 170, 28, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Lapis 4:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(190, 50, 60, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Lapis 5:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(190, 90, 50, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Lapis 6:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(190, 130, 47, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Lapis 1:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 180, 47, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Lapis 2:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 220, 50, 30);

        UserUID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserUIDActionPerformed(evt);
            }
        });
        getContentPane().add(UserUID);
        UserUID.setBounds(70, 10, 80, 30);

        Lapis2.setEnabled(false);
        getContentPane().add(Lapis2);
        Lapis2.setBounds(80, 220, 50, 30);

        ItemID.setEnabled(false);
        getContentPane().add(ItemID);
        ItemID.setBounds(70, 50, 80, 30);

        Lapis4.setEnabled(false);
        Lapis4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lapis4ActionPerformed(evt);
            }
        });
        getContentPane().add(Lapis4);
        Lapis4.setBounds(240, 50, 60, 30);

        Lapis3.setEnabled(false);
        getContentPane().add(Lapis3);
        Lapis3.setBounds(240, 10, 60, 30);

        Type.setEnabled(false);
        getContentPane().add(Type);
        Type.setBounds(70, 90, 80, 30);

        TypeID.setEnabled(false);
        getContentPane().add(TypeID);
        TypeID.setBounds(70, 130, 80, 30);

        Lapis1.setEnabled(false);
        getContentPane().add(Lapis1);
        Lapis1.setBounds(80, 180, 50, 30);

        strrr.setEnabled(false);
        getContentPane().add(strrr);
        strrr.setBounds(240, 170, 60, 30);

        Lapis5.setEnabled(false);
        Lapis5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lapis5ActionPerformed(evt);
            }
        });
        getContentPane().add(Lapis5);
        Lapis5.setBounds(240, 90, 60, 30);

        Lapis6.setEnabled(false);
        getContentPane().add(Lapis6);
        Lapis6.setBounds(240, 130, 60, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DEX:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(210, 210, 30, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("REC:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(370, 10, 28, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("LUC:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(370, 50, 30, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("WIS:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(370, 130, 30, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Enchant Type:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(340, 210, 120, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("INT:");
        jLabel17.setToolTipText("");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(370, 90, 30, 30);

        recrr.setEnabled(false);
        getContentPane().add(recrr);
        recrr.setBounds(400, 10, 60, 30);

        lucrr.setEnabled(false);
        getContentPane().add(lucrr);
        lucrr.setBounds(400, 50, 60, 30);

        intrr.setEnabled(false);
        getContentPane().add(intrr);
        intrr.setBounds(400, 90, 60, 30);

        wisrr.setEnabled(false);
        getContentPane().add(wisrr);
        wisrr.setBounds(400, 130, 60, 30);

        dexrr.setEnabled(false);
        getContentPane().add(dexrr);
        dexrr.setBounds(240, 210, 60, 30);

        EnchantType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Enchant", "Armor", "Weapon", "Cape" }));
        EnchantType.setEnabled(false);
        getContentPane().add(EnchantType);
        EnchantType.setBounds(430, 210, 160, 30);

        Search.setBackground(new java.awt.Color(0, 51, 102));
        Search.setForeground(new java.awt.Color(255, 255, 255));
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search);
        Search.setBounds(600, 10, 110, 23);

        Update.setBackground(new java.awt.Color(0, 51, 102));
        Update.setForeground(new java.awt.Color(255, 255, 255));
        Update.setText("Update");
        Update.setEnabled(false);
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update);
        Update.setBounds(600, 50, 110, 23);

        jButton3.setBackground(new java.awt.Color(0, 51, 102));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(600, 90, 110, 23);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("HP:");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(370, 170, 30, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("SP:");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(500, 10, 30, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("MP:");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(503, 60, 30, 30);

        hprr.setEnabled(false);
        getContentPane().add(hprr);
        hprr.setBounds(400, 170, 60, 30);

        sprr.setEnabled(false);
        getContentPane().add(sprr);
        sprr.setBounds(530, 10, 50, 30);

        mprr.setEnabled(false);
        getContentPane().add(mprr);
        mprr.setBounds(530, 60, 50, 30);

        Responsavel.setEnabled(false);
        Responsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResponsavelActionPerformed(evt);
            }
        });
        getContentPane().add(Responsavel);
        Responsavel.setBounds(560, 140, 150, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Responsible:");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(480, 140, 77, 30);

        JFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SY---Tigers-Claw-news.jpg"))); // NOI18N
        getContentPane().add(JFundo);
        JFundo.setBounds(0, 0, 744, 282);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserUIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserUIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserUIDActionPerformed

    private void Lapis4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lapis4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lapis4ActionPerformed

    private void Lapis5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lapis5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lapis5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new JBLogin().setVisible(true);
        this.dispose();
        this.setResizable(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        try {
            Conexao con = new Conexao();
            String SQL = "select * from PS_GameData.dbo.UserStoredItems where UserUID=? and Slot=0";
            PreparedStatement ps = con.getConexao().prepareStatement(SQL);
            ps.setString(1, UserUID.getText());
            ResultSet registros = ps.executeQuery();
            registros.next();
            int Am = registros.getInt("Slot");
            String I = registros.getString("ItemID");
            String T = registros.getString("Type");
            String TI = registros.getString("TypeID");
            String Gem1 = registros.getString("Gem1");
            String Gem2 = registros.getString("Gem2");
            String Gem3 = registros.getString("Gem3");
            String Gem4 = registros.getString("Gem4");
            String Gem5 = registros.getString("Gem5");
            String Gem6 = registros.getString("Gem6");
            if (Am != 1) {
                ItemID.setEnabled(true);
                ItemID.setText(I);
                Type.setEnabled(true);
                Type.setText(T);
                TypeID.setEnabled(true);
                TypeID.setText(TI);
                EnchantType.setEnabled(true);
                Update.setEnabled(true);
                UserUID.setEnabled(false);
                Search.setEnabled(false);
                strrr.setEnabled(true);
                strrr.setText("00");
                dexrr.setEnabled(true);
                dexrr.setText("00");
                lucrr.setEnabled(true);
                lucrr.setText("00");
                intrr.setEnabled(true);
                intrr.setText("00");
                recrr.setEnabled(true);
                recrr.setText("00");
                wisrr.setEnabled(true);
                wisrr.setText("00");
                hprr.setEnabled(true);
                hprr.setText("00");
                mprr.setEnabled(true);
                mprr.setText("00");
                sprr.setEnabled(true);
                sprr.setText("00");
                Lapis1.setEnabled(true);
                Lapis1.setText(Gem1);
                Lapis2.setEnabled(true);
                Lapis2.setText(Gem2);
                Lapis3.setEnabled(true);
                Lapis3.setText(Gem3);
                Lapis4.setEnabled(true);
                Lapis4.setText(Gem4);
                Lapis5.setEnabled(true);
                Lapis5.setText(Gem5);
                Lapis6.setEnabled(true);
                Lapis6.setText(Gem6);
                Responsavel.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(null, "Nothing at warehouse in Slot 1");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: Nothing at warehouse in Slot 1");
        }

    }//GEN-LAST:event_SearchActionPerformed

    private void ResponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResponsavelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResponsavelActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        try {
            if (UserUID.getText() != null) {
                if (EnchantType.getSelectedIndex() == 0) {
                    Conexao con = new Conexao();
                    String SQL = "Update PS_GameData.dbo.UserStoredItems set Craftname=?, Gem1=?, Gem2=?, Gem3=?, Gem4=?, Gem5=?, Gem6=?, ItemID =?, Type =?, TypeID =? where UserUID=? and Slot=0";
                    PreparedStatement ps = con.getConexao().prepareStatement(SQL);
                    String CraftName = "" + strrr.getText() + "" + dexrr.getText() + "" + recrr.getText() + "" + intrr.getText() + "" + wisrr.getText() + "" + lucrr.getText() + "" + hprr.getText() + "" + mprr.getText() + "" + sprr.getText() + "00";
                    ps.setString(1, CraftName);
                    ps.setString(2, Lapis1.getText());
                    ps.setString(3, Lapis2.getText());
                    ps.setString(4, Lapis3.getText());
                    ps.setString(5, Lapis4.getText());
                    ps.setString(6, Lapis5.getText());
                    ps.setString(7, Lapis6.getText());
                    ps.setString(8, ItemID.getText());
                    ps.setString(9, Type.getText());
                    ps.setString(10, TypeID.getText());
                    ps.setString(11, UserUID.getText());
                    int registros = ps.executeUpdate();
                    if (registros > 0) {
                        JOptionPane.showMessageDialog(null, "Item edited Sucessfully");
                        String data = "dd/MM/yyyy";
                        String hora = "h:mm - a";
                        String data1, hora1;
                        java.util.Date agora = new java.util.Date();;
                        SimpleDateFormat formata = new SimpleDateFormat(data);
                        data1 = formata.format(agora);
                        formata = new SimpleDateFormat(hora);
                        hora1 = formata.format(agora);
                        Conexao con1 = new Conexao();
                        String SQL1 = "INSERT INTO PS_ActionPerformed.dbo.Action values(?,'Edit Item',?,?,?)";
                        PreparedStatement ps1 = con1.getConexao().prepareStatement(SQL1);
                        ps1.setString(1, Responsavel.getText());
                        ps1.setString(2, data1);
                        ps1.setString(3, hora1);
                        ps1.setString(4, Responsavel.getText());
                        int registros1 = ps1.executeUpdate();
                        Update.setEnabled(false);
                        UserUID.setEnabled(true);
                        Search.setEnabled(true);
                        strrr.setEnabled(false);
                        EnchantType.setEnabled(false);
                        ItemID.setEnabled(false);
                        ItemID.setText("");
                        Type.setEnabled(false);
                        Type.setText("");
                        TypeID.setEnabled(false);
                        TypeID.setText("");
                        strrr.setText("");
                        dexrr.setEnabled(false);
                        dexrr.setText("");
                        lucrr.setEnabled(false);
                        lucrr.setText("");
                        intrr.setEnabled(false);
                        intrr.setText("");
                        recrr.setEnabled(false);
                        recrr.setText("");
                        wisrr.setEnabled(false);
                        wisrr.setText("");
                        hprr.setEnabled(false);
                        hprr.setText("");
                        mprr.setEnabled(false);
                        mprr.setText("");
                        sprr.setEnabled(false);
                        sprr.setText("");
                        Lapis1.setEnabled(false);
                        Lapis1.setText("");
                        Lapis2.setEnabled(false);
                        Lapis2.setText("");
                        Lapis3.setEnabled(false);
                        Lapis3.setText("");
                        Lapis4.setEnabled(false);
                        Lapis4.setText("");
                        Lapis5.setEnabled(false);
                        Lapis5.setText("");
                        Lapis6.setEnabled(false);
                        Lapis6.setText("");
                        Responsavel.setEnabled(false);
                    } else {
                        JOptionPane.showMessageDialog(null, "Invalid Lapis TypeID");;
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid Lapis TypeID");
                }
                if (EnchantType.getSelectedIndex() == 1) {
                    Conexao con = new Conexao();
                    String SQL = "Update PS_GameData.dbo.UserStoredItems set Craftname=?, Gem1=?, Gem2=?, Gem3=?, Gem4=?, Gem5=?, Gem6=?, ItemID =?, Type =?, TypeID =? where UserUID=? and Slot=0";
                    PreparedStatement ps = con.getConexao().prepareStatement(SQL);
                    String CraftName = "" + strrr.getText() + "" + dexrr.getText() + "" + recrr.getText() + "" + intrr.getText() + "" + wisrr.getText() + "" + lucrr.getText() + "" + hprr.getText() + "" + mprr.getText() + "" + sprr.getText() + "70";
                    ps.setString(1, CraftName);
                    ps.setString(2, Lapis1.getText());
                    ps.setString(3, Lapis2.getText());
                    ps.setString(4, Lapis3.getText());
                    ps.setString(5, Lapis4.getText());
                    ps.setString(6, Lapis5.getText());
                    ps.setString(7, Lapis6.getText());
                    ps.setString(8, ItemID.getText());
                    ps.setString(9, Type.getText());
                    ps.setString(10, TypeID.getText());
                    ps.setString(11, UserUID.getText());
                    int registros = ps.executeUpdate();
                    if (registros > 0) {
                        JOptionPane.showMessageDialog(null, "Item edited Sucessfully");
                        String data = "dd/MM/yyyy";
                        String hora = "h:mm - a";
                        String data1, hora1;
                        java.util.Date agora = new java.util.Date();;
                        SimpleDateFormat formata = new SimpleDateFormat(data);
                        data1 = formata.format(agora);
                        formata = new SimpleDateFormat(hora);
                        hora1 = formata.format(agora);
                        Conexao con1 = new Conexao();
                        String SQL1 = "INSERT INTO PS_ActionPerformed.dbo.Action values(?,'Edit Item',?,?,?)";
                        PreparedStatement ps1 = con1.getConexao().prepareStatement(SQL1);
                        ps1.setString(1, Responsavel.getText());
                        ps1.setString(2, data1);
                        ps1.setString(3, hora1);
                        ps1.setString(4, Responsavel.getText());
                        int registros1 = ps1.executeUpdate();
                        Update.setEnabled(false);
                        UserUID.setEnabled(true);
                        Search.setEnabled(true);
                        strrr.setEnabled(false);
                        EnchantType.setEnabled(false);
                        ItemID.setEnabled(false);
                        ItemID.setText("");
                        Type.setEnabled(false);
                        Type.setText("");
                        TypeID.setEnabled(false);
                        TypeID.setText("");
                        strrr.setText("");
                        dexrr.setEnabled(false);
                        dexrr.setText("");
                        lucrr.setEnabled(false);
                        lucrr.setText("");
                        intrr.setEnabled(false);
                        intrr.setText("");
                        recrr.setEnabled(false);
                        recrr.setText("");
                        wisrr.setEnabled(false);
                        wisrr.setText("");
                        hprr.setEnabled(false);
                        hprr.setText("");
                        mprr.setEnabled(false);
                        mprr.setText("");
                        sprr.setEnabled(false);
                        sprr.setText("");
                        Lapis1.setEnabled(false);
                        Lapis1.setText("");
                        Lapis2.setEnabled(false);
                        Lapis2.setText("");
                        Lapis3.setEnabled(false);
                        Lapis3.setText("");
                        Lapis4.setEnabled(false);
                        Lapis4.setText("");
                        Lapis5.setEnabled(false);
                        Lapis5.setText("");
                        Lapis6.setEnabled(false);
                        Lapis6.setText("");
                        Responsavel.setEnabled(false);
                    } else {
                        JOptionPane.showMessageDialog(null, "Invalid Lapis TypeID");;
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid Lapis TypeID");
                }
                if (EnchantType.getSelectedIndex() == 2) {
                    Conexao con = new Conexao();
                    String SQL = "Update PS_GameData.dbo.UserStoredItems set Craftname=?, Gem1=?, Gem2=?, Gem3=?, Gem4=?, Gem5=?, Gem6=?, ItemID =?, Type =?, TypeID =? where UserUID=? and Slot=0";
                    PreparedStatement ps = con.getConexao().prepareStatement(SQL);
                    String CraftName = "" + strrr.getText() + "" + dexrr.getText() + "" + recrr.getText() + "" + intrr.getText() + "" + wisrr.getText() + "" + lucrr.getText() + "" + hprr.getText() + "" + mprr.getText() + "" + sprr.getText() + "20";
                    ps.setString(1, CraftName);
                    ps.setString(2, Lapis1.getText());
                    ps.setString(3, Lapis2.getText());
                    ps.setString(4, Lapis3.getText());
                    ps.setString(5, Lapis4.getText());
                    ps.setString(6, Lapis5.getText());
                    ps.setString(7, Lapis6.getText());
                    ps.setString(8, ItemID.getText());
                    ps.setString(9, Type.getText());
                    ps.setString(10, TypeID.getText());
                    ps.setString(11, UserUID.getText());
                    int registros = ps.executeUpdate();
                    if (registros > 0) {
                        JOptionPane.showMessageDialog(null, "Item edited Sucessfully");
                        String data = "dd/MM/yyyy";
                        String hora = "h:mm - a";
                        String data1, hora1;
                        java.util.Date agora = new java.util.Date();;
                        SimpleDateFormat formata = new SimpleDateFormat(data);
                        data1 = formata.format(agora);
                        formata = new SimpleDateFormat(hora);
                        hora1 = formata.format(agora);
                        Conexao con1 = new Conexao();
                        String SQL1 = "INSERT INTO PS_ActionPerformed.dbo.Action values(?,'Edit Item',?,?,?)";
                        PreparedStatement ps1 = con1.getConexao().prepareStatement(SQL1);
                        ps1.setString(1, Responsavel.getText());
                        ps1.setString(2, data1);
                        ps1.setString(3, hora1);
                        ps1.setString(4, Responsavel.getText());
                        int registros1 = ps1.executeUpdate();
                        Update.setEnabled(false);
                        UserUID.setEnabled(true);
                        Search.setEnabled(true);
                        strrr.setEnabled(false);
                        EnchantType.setEnabled(false);
                        ItemID.setEnabled(false);
                        ItemID.setText("");
                        Type.setEnabled(false);
                        Type.setText("");
                        TypeID.setEnabled(false);
                        TypeID.setText("");
                        strrr.setText("");
                        dexrr.setEnabled(false);
                        dexrr.setText("");
                        lucrr.setEnabled(false);
                        lucrr.setText("");
                        intrr.setEnabled(false);
                        intrr.setText("");
                        recrr.setEnabled(false);
                        recrr.setText("");
                        wisrr.setEnabled(false);
                        wisrr.setText("");
                        hprr.setEnabled(false);
                        hprr.setText("");
                        mprr.setEnabled(false);
                        mprr.setText("");
                        sprr.setEnabled(false);
                        sprr.setText("");
                        Lapis1.setEnabled(false);
                        Lapis1.setText("");
                        Lapis2.setEnabled(false);
                        Lapis2.setText("");
                        Lapis3.setEnabled(false);
                        Lapis3.setText("");
                        Lapis4.setEnabled(false);
                        Lapis4.setText("");
                        Lapis5.setEnabled(false);
                        Lapis5.setText("");
                        Lapis6.setEnabled(false);
                        Lapis6.setText("");
                        Responsavel.setEnabled(false);
                    } else {
                        JOptionPane.showMessageDialog(null, "Invalid Lapis TypeID");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Invalid Lapis TypeID");
                }
                if (EnchantType.getSelectedIndex() == 3) {
                    Conexao con = new Conexao();
                    String SQL = "Update PS_GameData.dbo.UserStoredItems set Craftname=?, Gem1=?, Gem2=?, Gem3=?, Gem4=?, Gem5=?, Gem6=?, ItemID =?, Type =?, TypeID =? where UserUID=? and Slot=0";
                    PreparedStatement ps = con.getConexao().prepareStatement(SQL);
                    String CraftName = "" + strrr.getText() + "" + dexrr.getText() + "" + recrr.getText() + "" + intrr.getText() + "" + wisrr.getText() + "" + lucrr.getText() + "" + hprr.getText() + "" + mprr.getText() + "" + sprr.getText() + "70";
                    ps.setString(1, CraftName);
                    ps.setString(2, Lapis1.getText());
                    ps.setString(3, Lapis2.getText());
                    ps.setString(4, Lapis3.getText());
                    ps.setString(5, Lapis4.getText());
                    ps.setString(6, Lapis5.getText());
                    ps.setString(7, Lapis6.getText());
                    ps.setString(8, ItemID.getText());
                    ps.setString(9, Type.getText());
                    ps.setString(10, TypeID.getText());
                    ps.setString(11, UserUID.getText());
                    int registros = ps.executeUpdate();
                    if (registros > 0) {
                        JOptionPane.showMessageDialog(null, "Item edited Sucessfully");
                        String data = "dd/MM/yyyy";
                        String hora = "h:mm - a";
                        String data1, hora1;
                        java.util.Date agora = new java.util.Date();;
                        SimpleDateFormat formata = new SimpleDateFormat(data);
                        data1 = formata.format(agora);
                        formata = new SimpleDateFormat(hora);
                        hora1 = formata.format(agora);
                        Conexao con1 = new Conexao();
                        String SQL1 = "INSERT INTO PS_ActionPerformed.dbo.Action values(?,'Edit Item',?,?,?)";
                        PreparedStatement ps1 = con1.getConexao().prepareStatement(SQL1);
                        ps1.setString(1, Responsavel.getText());
                        ps1.setString(2, data1);
                        ps1.setString(3, hora1);
                        ps1.setString(4, Responsavel.getText());
                        int registros1 = ps1.executeUpdate();
                        Update.setEnabled(false);
                        UserUID.setEnabled(true);
                        Search.setEnabled(true);
                        strrr.setEnabled(false);
                        EnchantType.setEnabled(false);
                        ItemID.setEnabled(false);
                        ItemID.setText("");
                        Type.setEnabled(false);
                        Type.setText("");
                        TypeID.setEnabled(false);
                        TypeID.setText("");
                        strrr.setText("");
                        dexrr.setEnabled(false);
                        dexrr.setText("");
                        lucrr.setEnabled(false);
                        lucrr.setText("");
                        intrr.setEnabled(false);
                        intrr.setText("");
                        recrr.setEnabled(false);
                        recrr.setText("");
                        wisrr.setEnabled(false);
                        wisrr.setText("");
                        hprr.setEnabled(false);
                        hprr.setText("");
                        mprr.setEnabled(false);
                        mprr.setText("");
                        sprr.setEnabled(false);
                        sprr.setText("");
                        Lapis1.setEnabled(false);
                        Lapis1.setText("");
                        Lapis2.setEnabled(false);
                        Lapis2.setText("");
                        Lapis3.setEnabled(false);
                        Lapis3.setText("");
                        Lapis4.setEnabled(false);
                        Lapis4.setText("");
                        Lapis5.setEnabled(false);
                        Lapis5.setText("");
                        Lapis6.setEnabled(false);
                        Lapis6.setText("");
                        Responsavel.setEnabled(false);
                    } else {
                        JOptionPane.showMessageDialog(null, "Invalid Lapis TypeID");;
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid Lapis TypeID");
                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Lapis TypeID");
        }
    }//GEN-LAST:event_UpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox EnchantType;
    private javax.swing.JTextField ItemID;
    private javax.swing.JLabel JFundo;
    private javax.swing.JTextField Lapis1;
    private javax.swing.JTextField Lapis2;
    private javax.swing.JTextField Lapis3;
    private javax.swing.JTextField Lapis4;
    private javax.swing.JTextField Lapis5;
    private javax.swing.JTextField Lapis6;
    private javax.swing.JTextField Responsavel;
    private javax.swing.JButton Search;
    private javax.swing.JTextField Type;
    private javax.swing.JTextField TypeID;
    private javax.swing.JButton Update;
    private javax.swing.JTextField UserUID;
    private javax.swing.JTextField dexrr;
    private javax.swing.JTextField hprr;
    private javax.swing.JTextField intrr;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lucrr;
    private javax.swing.JTextField mprr;
    private javax.swing.JTextField recrr;
    private javax.swing.JTextField sprr;
    private javax.swing.JTextField strrr;
    private javax.swing.JTextField wisrr;
    // End of variables declaration//GEN-END:variables
}
