/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tool;

import SQL.Conexao;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorgi Luiz Bolonhezi Dias
 */
 
public class EditDrop extends javax.swing.JFrame {

    /**
     * Creates new form EditDrop
     */
    public EditDrop() {
        initComponents();
        setSize(750, 309);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MobID = new javax.swing.JTextField();
        Grade = new javax.swing.JTextField();
        DropRate = new javax.swing.JTextField();
        ItemOrder = new javax.swing.JTextField();
        jResponsavel = new javax.swing.JTextField();
        jUpdate = new javax.swing.JButton();
        jMenu = new javax.swing.JButton();
        jFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Drop - Panel");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mob ID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 70, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Grade:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 60, 46, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DropRate:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(360, 20, 80, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Item Order:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(350, 70, 90, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Responsible:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(290, 110, 120, 30);
        getContentPane().add(MobID);
        MobID.setBounds(80, 20, 80, 30);
        getContentPane().add(Grade);
        Grade.setBounds(80, 60, 80, 30);
        getContentPane().add(DropRate);
        DropRate.setBounds(450, 20, 70, 30);
        getContentPane().add(ItemOrder);
        ItemOrder.setBounds(450, 70, 70, 30);

        jResponsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResponsavelActionPerformed(evt);
            }
        });
        getContentPane().add(jResponsavel);
        jResponsavel.setBounds(390, 110, 160, 30);

        jUpdate.setBackground(new java.awt.Color(0, 51, 102));
        jUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jUpdate.setText("Update");
        jUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(jUpdate);
        jUpdate.setBounds(603, 10, 120, 23);

        jMenu.setBackground(new java.awt.Color(0, 51, 102));
        jMenu.setForeground(new java.awt.Color(255, 255, 255));
        jMenu.setText("Menu");
        jMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jMenu);
        jMenu.setBounds(639, 50, 80, 23);

        jFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LionNews.jpg"))); // NOI18N
        getContentPane().add(jFundo);
        jFundo.setBounds(0, 0, 744, 282);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jResponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResponsavelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jResponsavelActionPerformed

    private void jMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuActionPerformed
        new JBLogin().setVisible(true);
        this.dispose();
        this.setResizable(false);
    }//GEN-LAST:event_jMenuActionPerformed

    private void jUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateActionPerformed
        try {
            if (ItemOrder.getText() != null) {
                if (MobID.getText() != null) {
                    if (DropRate.getText() != null) {
                        if (Grade.getText() != null) {
                            Conexao con = new Conexao();
                            String SQL = "Update PS_GameDefs.dbo.MobItems set Grade=? , DropRate =? where MobID=? and ItemOrder=?";
                            PreparedStatement ps = con.getConexao().prepareStatement(SQL);
                            ps.setString(1, Grade.getText());
                            ps.setString(2, DropRate.getText());
                            ps.setString(3, MobID.getText());
                            ps.setString(4, ItemOrder.getText());
                            int registros = ps.executeUpdate();
                            if (registros > 0) {
                                JOptionPane.showMessageDialog(null, "Updated Sucessfully!");
                                String data = "dd/MM/yyyy";
                                String hora = "h:mm - a";
                                String data1, hora1;
                                java.util.Date agora = new java.util.Date();;
                                SimpleDateFormat formata = new SimpleDateFormat(data);
                                data1 = formata.format(agora);
                                formata = new SimpleDateFormat(hora);
                                hora1 = formata.format(agora);
                                Conexao con1 = new Conexao();
                                String SQL1 = "INSERT INTO PS_ActionPerformed.dbo.Action values(?,'Edit Drop',?,?,?)";
                                PreparedStatement ps1 = con1.getConexao().prepareStatement(SQL1);
                                ps1.setString(1, jResponsavel.getText());
                                ps1.setString(2, data1);
                                ps1.setString(3, hora1);
                                ps1.setString(4, jResponsavel.getText());
                                int registros1 = ps1.executeUpdate();
                                ItemOrder.setText("");
                                MobID.setText("");
                                DropRate.setText("");
                                Grade.setText("");
                            } else {
                                JOptionPane.showMessageDialog(null, "Invalid Edit.");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Please Insert Grade.");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Please Insert DropRate.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Please Insert MonsterID");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please Insert ItemOrder");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Connection Error");
        }
    }//GEN-LAST:event_jUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditDrop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditDrop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditDrop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditDrop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditDrop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DropRate;
    private javax.swing.JTextField Grade;
    private javax.swing.JTextField ItemOrder;
    private javax.swing.JTextField MobID;
    private javax.swing.JLabel jFundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jMenu;
    private javax.swing.JTextField jResponsavel;
    private javax.swing.JButton jUpdate;
    // End of variables declaration//GEN-END:variables
}
