/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tool;

import SQL.Conexao;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorgi Luiz Bolonhezi Dias
 */
 
public class FC extends javax.swing.JFrame {

    /**
     * Creates new form FC
     */
    public FC() {
        initComponents();
        setSize(750, 309);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jUID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jResponsavel = new javax.swing.JTextField();
        jFC = new javax.swing.JButton();
        jMenu = new javax.swing.JButton();
        jFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Faction Change");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User UID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(410, 20, 67, 30);
        getContentPane().add(jUID);
        jUID.setBounds(480, 20, 50, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Responsible:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(360, 120, 100, 30);
        getContentPane().add(jResponsavel);
        jResponsavel.setBounds(450, 120, 110, 30);

        jFC.setBackground(new java.awt.Color(0, 0, 102));
        jFC.setForeground(new java.awt.Color(255, 255, 255));
        jFC.setText("FC");
        jFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFCActionPerformed(evt);
            }
        });
        getContentPane().add(jFC);
        jFC.setBounds(425, 240, 80, 23);

        jMenu.setBackground(new java.awt.Color(0, 0, 102));
        jMenu.setForeground(new java.awt.Color(255, 255, 255));
        jMenu.setText("Menu");
        jMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jMenu);
        jMenu.setBounds(600, 240, 59, 23);

        jFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LionNews.jpg"))); // NOI18N
        getContentPane().add(jFundo);
        jFundo.setBounds(0, 0, 744, 282);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFCActionPerformed
                try {
            if (jUID.getText() != null) {
                if (jResponsavel.getText() != null) {
                    Conexao con = new Conexao();
                    String SQL = "UPDATE PS_GameData.dbo.UserMaxGrow SET Country=(\n"
                            + "CASE \n"
                            + " WHEN Country = 0 THEN 1 \n"
                            + " WHEN Country = 1 THEN 0 \n"
                            + "END)\n"
                            + "WHERE UserUID = ?";
                    PreparedStatement ps = con.getConexao().prepareStatement(SQL);
                    ps.setString(1, jUID.getText());
                    int registros = ps.executeUpdate();
                    if (registros > 0) {
                        String data = "dd/MM/yyyy";
                        String hora = "h:mm - a";
                        String data1, hora1;
                        java.util.Date agora = new java.util.Date();;
                        SimpleDateFormat formata = new SimpleDateFormat(data);
                        data1 = formata.format(agora);
                        formata = new SimpleDateFormat(hora);
                        hora1 = formata.format(agora);
                        Conexao con1 = new Conexao();
                        String SQL1 = "INSERT INTO PS_ActionPerformed.dbo.Action values(?,'Faction Change',?,?,?)";
                        PreparedStatement ps1 = con1.getConexao().prepareStatement(SQL1);
                        ps1.setString(1, jResponsavel.getText());
                        ps1.setString(2, data1);
                        ps1.setString(3, hora1);
                        ps1.setString(4, jResponsavel.getText());
                        int registros1 = ps1.executeUpdate();
                        jUID.setText("");
                        jResponsavel.setText("");
                        JOptionPane.showMessageDialog(null, "FCed Sucessfully!");
                    } else {
                        JOptionPane.showMessageDialog(null, "Invalid FC.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Please Insert Responsible.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please Insert UserUID.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Connection Error");
        }
    }//GEN-LAST:event_jFCActionPerformed

    private void jMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuActionPerformed
            new JBLogin().setVisible(true);
            this.dispose();
            this.setResizable(false);
    }//GEN-LAST:event_jMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jFC;
    private javax.swing.JLabel jFundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jMenu;
    private javax.swing.JTextField jResponsavel;
    private javax.swing.JTextField jUID;
    // End of variables declaration//GEN-END:variables
}
