/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tool;

import SQL.Conexao;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorgi Luiz Bolonhezi Dias
 */
 
public class Guild extends javax.swing.JFrame {

    /**
     * Creates new form Guild
     */
    public Guild() {
        initComponents();
        setSize(750, 310);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jGuild = new javax.swing.JTextField();
        jUID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jUpdate = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMasterName = new javax.swing.JTextField();
        jMasterID = new javax.swing.JTextField();
        jFundo = new javax.swing.JLabel();
        Reference = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Guild - Panel");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Guild:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 100, 50, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Master UserID:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 140, 110, 30);
        getContentPane().add(jGuild);
        jGuild.setBounds(390, 100, 110, 30);

        jUID.setEnabled(false);
        getContentPane().add(jUID);
        jUID.setBounds(460, 140, 80, 30);

        jButton1.setBackground(new java.awt.Color(0, 51, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(640, 10, 90, 23);

        jUpdate.setBackground(new java.awt.Color(0, 51, 102));
        jUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jUpdate.setText("Update");
        jUpdate.setEnabled(false);
        jUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(jUpdate);
        jUpdate.setBounds(640, 40, 90, 23);

        jButton3.setBackground(new java.awt.Color(0, 51, 102));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(640, 70, 90, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Master Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(420, 190, 110, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Master CharID:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(430, 230, 110, 30);

        jMasterName.setEnabled(false);
        getContentPane().add(jMasterName);
        jMasterName.setBounds(540, 190, 100, 30);

        jMasterID.setEnabled(false);
        getContentPane().add(jMasterID);
        jMasterID.setBounds(540, 230, 100, 30);

        jFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LionNews.jpg"))); // NOI18N
        getContentPane().add(jFundo);
        jFundo.setBounds(0, 0, 744, 282);

        Reference.setText("jLabel5");
        getContentPane().add(Reference);
        Reference.setBounds(450, 260, 34, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new JBLogin().setVisible(true);
        this.dispose();
        this.setResizable(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            try {
                Conexao con = new Conexao();
                String SQL = "SELECT * FROM PS_GameData.dbo.Guilds WHERE GuildName=?";
                PreparedStatement ps = con.getConexao().prepareStatement(SQL);
                ps.setString(1, jGuild.getText());
                ResultSet registros = ps.executeQuery();
                registros.next();
                String Am = registros.getString("GuildName");
                String Em = registros.getString("MasterUserID");
                int Im = registros.getInt("MasterCharID");
                String Aux2 = Integer.toString(Im);
                String Om = registros.getString("MasterName");
                if(Am!=null){
                    jGuild.setText(Am);
                    jUID.setText(Em);
                    jMasterName.setText(Om);
                    jMasterID.setText(Aux2);
                    jUID.setEnabled(true);
                    jMasterName.setEnabled(true);
                    jMasterID.setEnabled(true);
                    jUpdate.setEnabled(true);
                    Reference.setText(Am);
                }else{
                    JOptionPane.showMessageDialog(null, "Guild Not Found");
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: Not Found");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateActionPerformed
            try {
                Conexao con = new Conexao();
                String SQL = "UPDATE PS_GameData.dbo.Guilds SET GuildName=?, MasterUserID=?, MasterCharID=?, MasterName=? WHERE GuildName=?";
                PreparedStatement ps = con.getConexao().prepareStatement(SQL);
                ps.setString(1, jGuild.getText());
                ps.setString(2, jUID.getText());
                ps.setString(3, jMasterID.getText());
                ps.setString(4, jMasterName.getText());
                ps.setString(5, Reference.getText());
                int registros = ps.executeUpdate();
                if(registros!=0){
                    jGuild.setText("");
                    jUID.setText("");
                    jMasterName.setText("");
                    jMasterID.setText("");
                    Reference.setText("");
                    jUID.setEnabled(false);
                    jMasterName.setEnabled(false);
                    jMasterID.setEnabled(false);
                    jUpdate.setEnabled(false);
                    JOptionPane.showMessageDialog(null, "Updated Sucessfully");
                }else{
                    JOptionPane.showMessageDialog(null, "Guild Not Found");
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: Not Found");
        }
    }//GEN-LAST:event_jUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guild.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guild.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guild.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guild.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guild().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Reference;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jFundo;
    private javax.swing.JTextField jGuild;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jMasterID;
    private javax.swing.JTextField jMasterName;
    private javax.swing.JTextField jUID;
    private javax.swing.JButton jUpdate;
    // End of variables declaration//GEN-END:variables
}
