using Imgeneus.Game.Skills;
using Imgeneus.World.Game.Attack;
using Imgeneus.World.Game.Session;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Imgeneus.World.Game.Skills
{
    public interface ISkillsManager : ISessionedService, IDisposable
    {
        /// <summary>
        /// Number for skill, generated by using item from inventory.
        /// </summary>
        public const byte ITEM_SKILL_NUMBER = 254;

        /// <summary>
        /// Inits skill manager.
        /// </summary>
        /// <param name="ownerId">who is using skills</param>
        /// <param name="skills">initial skills</param>
        /// <param name="skillPoint">free skill points</param>
        void Init(uint ownerId, IEnumerable<Skill> skills, ushort skillPoint = 0);

        /// <summary>
        /// Event, that is fired, when single target skill is used.
        /// </summary>
        event Action<uint, IKillable, Skill, AttackResult> OnUsedSkill;

        /// <summary>
        /// Event, that is fired, when range skill is used.
        /// </summary>
        event Action<uint, IKillable, Skill, AttackResult> OnUsedRangeSkill;

        /// <summary>
        /// Free skill points.
        /// </summary>
        ushort SkillPoints { get; }

        /// <summary>
        /// Tries to set new value for skill points nad save it to db
        /// </summary>
        /// <param name="skillPoint">value of skill points</param>
        /// <returns>true if success</returns>
        bool TrySetSkillPoints(ushort skillPoint);

        /// <summary>
        /// Collection of available skills.
        /// </summary>
        ConcurrentDictionary<byte, Skill> Skills { get; }

        /// <summary>
        /// Player learns new skill.
        /// </summary>
        /// <param name="skillId">skill id</param>
        /// <param name="skillLevel">skill level</param>
        /// <returns>successful or not</returns>
        (bool Ok, Skill Skill) TryLearnNewSkill(ushort skillId, byte skillLevel);

        /// <summary>
        /// Checks if it's enough sp and mp in order to use a skill.
        /// </summary>
        /// <param name="skill">skill, that character wants to use</param>
        bool CanUseSkill(Skill skill, IKillable target, out AttackSuccess success);

        /// <summary>
        /// Use skill on <see cref="IKillable"/>
        /// </summary>
        void UseSkill(Skill skill, IKiller skillOwner, IKillable target = null);

        /// <summary>
        /// Clears skills and adds skill points.
        /// </summary>
        bool ResetSkills();

        /// <summary>
        /// Triggers send reset skills for player.
        /// </summary>
        event Action OnResetSkills;

        /// <summary>
        /// When "Charge" skill was used the last time?
        /// </summary>
        DateTime? ChargeUsedLastTime { get; }

        /// <summary>
        /// To which skills there is resistanse.
        /// </summary>
        IList<ushort> ResistSkills { get; }

        /// <summary>
        /// When used skill can be used again?
        /// </summary>
        ConcurrentDictionary<ushort, DateTime> Cooldowns { get; }
    }
}
